# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Deploy service

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pauldaniv/yellow-taxi-scripts/build-java:latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache gradle dependencies
        uses: actions/cache@v3.2.4
        env:
          cache-name: cache-gradle
        with:
          # gradle cache files are stored in `~/.gradle` on Linux/macOS
          path: ~/.gradle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Run Build
        run: ci build
      - name: Run Tests
        run: ci test
      - name: Publish artifacts
        if: github.ref == 'refs/heads/main'
        run: ci publish
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: ci deploy
